web_checks:
  # base_minima
  - name: observabilidade-public
    url: https://observabilidade.escossio.dev.br/
    expected_status: 200
    timeout: 5
    follow_redirects: true

  # segunda_linha
  - name: grafana-local
    url: http://127.0.0.1:3000/
    expected_status: 200
    timeout: 5
    follow_redirects: true

  - name: zabbix-frontend-alt-port
    url: http://127.0.0.1:8081/
    expected_status: 200
    timeout: 5
    follow_redirects: true

  # fora_de_escopo_nesta_rodada
